name: "Build RavenOS"

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        klipper_variant:
          - klipper
          - kalico

        board:
          - uefi-x86
          - rpi4b
          - bigtreetech-cb1
          - bigtreetech-cb2

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/cache@v4
        with:
          key: ${{ matrix.board }}
          path: |
            build/cache
            build/output/debs
            build/output/packages-hashed

      - name: Setup our userpatches
        run: |
          rm -rf $(pwd)/build/userpatches
          ln -sf $(pwd)/userpatches $(pwd)/build/userpatches

      - name: Build for ${{ matrix.board }}
        run: |
          ./build/compile.sh ravenos \
              BOARD="${{ matrix.board }}" \
              KLIPPER_VARIANT="${{ matrix.klipper_variant }}"

      - uses: actions/upload-artifact@v4
        with:
          name: RavenOS-${{ matrix.board }}-${{ matrix.klipper_variant }}
          path: build/output/images/*
          compression-level: 9
